# Generated by Django 5.2.8 on 2025-12-01 13:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=255)),
                ('key_hash', models.CharField(db_index=True, help_text='SHA256 hash of the API key', max_length=64, unique=True)),
                ('prefix', models.CharField(help_text='First 8 characters of the key (for identification)', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('scopes', models.JSONField(default=list, help_text='List of allowed scopes/permissions')),
                ('custom_rate_limit', models.IntegerField(blank=True, help_text='Custom rate limit for this key (requests per minute)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date (null = never expires)', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(help_text='User this API key belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], db_index=True, max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['username', '-attempted_at'], name='core_logina_usernam_de1067_idx'), models.Index(fields=['ip_address', '-attempted_at'], name='core_logina_ip_addr_230faa_idx'), models.Index(fields=['status', '-attempted_at'], name='core_logina_status_12da03_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_rate_limiting', models.BooleanField(default=True, help_text='Enable global rate limiting')),
                ('rate_limit_requests', models.IntegerField(default=100, help_text='Number of requests allowed per time window', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('rate_limit_window', models.IntegerField(default=60, help_text='Time window in seconds for rate limiting', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)])),
                ('api_rate_limit_anonymous', models.IntegerField(default=20, help_text='Requests per minute for anonymous users', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('api_rate_limit_authenticated', models.IntegerField(default=100, help_text='Requests per minute for authenticated users', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)])),
                ('login_rate_limit', models.IntegerField(default=5, help_text='Login attempts allowed per IP per time window', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('login_rate_window', models.IntegerField(default=300, help_text='Time window in seconds for login rate limiting', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(3600)])),
                ('enable_brute_force_protection', models.BooleanField(default=True, help_text='Enable brute force attack protection')),
                ('max_login_attempts', models.IntegerField(default=5, help_text='Maximum failed login attempts before account lockout', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)])),
                ('account_lockout_duration', models.IntegerField(default=900, help_text='Account lockout duration in seconds (default 15 minutes)', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)])),
                ('enable_ip_blacklist', models.BooleanField(default=True, help_text='Enable IP blacklisting for suspicious activity')),
                ('ip_blacklist_threshold', models.IntegerField(default=10, help_text='Failed attempts before IP is blacklisted', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(100)])),
                ('ip_blacklist_duration', models.IntegerField(default=3600, help_text='IP blacklist duration in seconds (default 1 hour)', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(86400)])),
                ('session_timeout', models.IntegerField(default=1800, help_text='Session timeout in seconds (default 30 minutes)', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(86400)])),
                ('max_sessions_per_user', models.IntegerField(default=5, help_text='Maximum concurrent sessions per user', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('session_refresh_on_activity', models.BooleanField(default=True, help_text='Refresh session timeout on user activity')),
                ('min_password_length', models.IntegerField(default=8, help_text='Minimum password length', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(128)])),
                ('require_uppercase', models.BooleanField(default=True, help_text='Require at least one uppercase letter')),
                ('require_lowercase', models.BooleanField(default=True, help_text='Require at least one lowercase letter')),
                ('require_digit', models.BooleanField(default=True, help_text='Require at least one digit')),
                ('require_special_char', models.BooleanField(default=True, help_text='Require at least one special character')),
                ('password_expiry_days', models.IntegerField(default=90, help_text='Password expiry in days (0 = never expires)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('prevent_password_reuse', models.IntegerField(default=5, help_text='Number of previous passwords to prevent reuse (0 = disabled)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('enable_2fa', models.BooleanField(default=False, help_text='Enable two-factor authentication')),
                ('require_2fa_for_admin', models.BooleanField(default=False, help_text='Require 2FA for admin users')),
                ('enable_captcha', models.BooleanField(default=False, help_text='Enable CAPTCHA on login')),
                ('captcha_after_failed_attempts', models.IntegerField(default=3, help_text='Show CAPTCHA after N failed attempts', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('enable_security_headers', models.BooleanField(default=True, help_text='Enable security headers (HSTS, CSP, etc.)')),
                ('hsts_max_age', models.IntegerField(default=31536000, help_text='HTTP Strict Transport Security max age in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('enable_csp', models.BooleanField(default=True, help_text='Enable Content Security Policy')),
                ('enable_audit_logging', models.BooleanField(default=True, help_text='Enable comprehensive audit logging')),
                ('log_failed_logins', models.BooleanField(default=True, help_text='Log all failed login attempts')),
                ('log_successful_logins', models.BooleanField(default=True, help_text='Log successful logins')),
                ('log_api_requests', models.BooleanField(default=False, help_text='Log all API requests (may impact performance)')),
                ('audit_log_retention_days', models.IntegerField(default=90, help_text='Days to retain audit logs', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('ip_whitelist', models.JSONField(blank=True, default=list, help_text='List of whitelisted IP addresses (empty = all allowed)')),
                ('require_whitelist_for_admin', models.BooleanField(default=False, help_text='Require IP whitelist for admin panel access')),
                ('require_api_key', models.BooleanField(default=False, help_text='Require API key for all API requests')),
                ('api_key_header_name', models.CharField(default='X-API-Key', help_text='Header name for API key authentication', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('is_permanent', models.BooleanField(default=False, help_text='Permanent blacklist (manual)')),
                ('is_auto', models.BooleanField(default=True, help_text='Auto-generated from failed attempts')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When auto-blacklist expires (null = permanent)', null=True)),
                ('failed_attempts_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who manually blacklisted (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-blacklisted_at'],
                'indexes': [models.Index(fields=['ip_address', 'expires_at'], name='core_ipblac_ip_addr_1a87cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('ip_blacklisted', 'IP Blacklisted'), ('ip_whitelisted', 'IP Whitelisted'), ('permission_denied', 'Permission Denied'), ('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('settings_changed', 'Settings Changed'), ('suspicious_activity', 'Suspicious Activity'), ('data_export', 'Data Export'), ('data_import', 'Data Import'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('role_changed', 'Role Changed')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=20)),
                ('description', models.TextField()),
                ('username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the event', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='core_securi_event_t_34c0be_idx'), models.Index(fields=['severity', '-created_at'], name='core_securi_severit_3ec17b_idx'), models.Index(fields=['user', '-created_at'], name='core_securi_user_id_d02b9b_idx'), models.Index(fields=['ip_address', '-created_at'], name='core_securi_ip_addr_1f2ae9_idx')],
            },
        ),
    ]
