# Generated by Django 5.2.8 on 2025-12-01 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('deployment', 'Deployment'), ('configuration', 'Configuration Change'), ('schema_change', 'Schema Change'), ('security_update', 'Security Update'), ('feature_added', 'Feature Added'), ('feature_removed', 'Feature Removed'), ('bug_fix', 'Bug Fix'), ('performance', 'Performance Optimization'), ('migration', 'Data Migration'), ('hotfix', 'Hotfix'), ('rollback', 'Rollback'), ('maintenance', 'Maintenance'), ('other', 'Other')], db_index=True, help_text='Type of change', max_length=30)),
                ('title', models.CharField(help_text='Brief title of the change', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the change')),
                ('version', models.CharField(blank=True, help_text='Version number (e.g., v1.2.3)', max_length=50, null=True)),
                ('impact_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', help_text='Impact level of the change', max_length=20)),
                ('affected_systems', models.JSONField(default=list, help_text='List of affected systems/modules')),
                ('change_request_id', models.CharField(blank=True, help_text='Reference to change request/ticket ID', max_length=100, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('emergency', 'Emergency (No Approval)')], default='approved', help_text='Approval status', max_length=20)),
                ('deployed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the change was deployed')),
                ('can_rollback', models.BooleanField(default=False, help_text='Whether this change can be rolled back')),
                ('rollback_instructions', models.TextField(blank=True, help_text='Instructions for rolling back this change')),
                ('rolled_back', models.BooleanField(db_index=True, default=False, help_text='Whether this change has been rolled back')),
                ('rolled_back_at', models.DateTimeField(blank=True, help_text='When the rollback was performed', null=True)),
                ('testing_notes', models.TextField(blank=True, help_text='Testing performed before deployment')),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='passed', help_text='Validation status', max_length=20)),
                ('documentation_url', models.URLField(blank=True, help_text='Link to detailed documentation', null=True)),
                ('jira_ticket', models.CharField(blank=True, help_text='Jira/ticket reference', max_length=100, null=True)),
                ('git_commit', models.CharField(blank=True, help_text='Git commit hash', max_length=40, null=True)),
                ('git_branch', models.CharField(blank=True, help_text='Git branch name', max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_changes', to=settings.AUTH_USER_MODEL)),
                ('rolled_back_by', models.ForeignKey(blank=True, help_text='User who performed the rollback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollbacks_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'ordering': ['-deployed_at'],
                'indexes': [models.Index(fields=['change_type', '-deployed_at'], name='core_change_change__cb3dca_idx'), models.Index(fields=['impact_level', '-deployed_at'], name='core_change_impact__fd2034_idx'), models.Index(fields=['rolled_back', '-deployed_at'], name='core_change_rolled__e3cb14_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Username (denormalized for faster queries)', max_length=150)),
                ('login_type', models.CharField(choices=[('password', 'Password'), ('magic_link', 'Magic Link'), ('api_key', 'API Key'), ('jwt_refresh', 'JWT Refresh'), ('social', 'Social Login'), ('sso', 'Single Sign-On')], default='password', help_text='Method used to authenticate', max_length=20)),
                ('success', models.BooleanField(db_index=True, default=True, help_text='Whether login was successful')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failed login (if applicable)', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address of the login attempt')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', help_text='Type of device used', max_length=20)),
                ('country', models.CharField(blank=True, help_text='Country code (ISO 3166-1 alpha-2)', max_length=2, null=True)),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100, null=True)),
                ('session_key', models.CharField(blank=True, help_text='Django session key', max_length=40, null=True)),
                ('login_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp of login attempt')),
                ('logout_at', models.DateTimeField(blank=True, help_text='Timestamp of logout (if applicable)', null=True)),
                ('session_duration', models.DurationField(blank=True, help_text='Duration of the session', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (referrer, etc.)')),
                ('user', models.ForeignKey(help_text='User who logged in', on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Login History',
                'verbose_name_plural': 'User Login Histories',
                'ordering': ['-login_at'],
                'indexes': [models.Index(fields=['user', '-login_at'], name='core_userlo_user_id_e2a050_idx'), models.Index(fields=['ip_address', '-login_at'], name='core_userlo_ip_addr_9d8d12_idx'), models.Index(fields=['username', '-login_at'], name='core_userlo_usernam_9bc305_idx'), models.Index(fields=['success', '-login_at'], name='core_userlo_success_55de1d_idx')],
            },
        ),
    ]
