# Generated by Django 5.2.8 on 2025-12-02 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_changelog_userloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_document_sharing',
            field=models.BooleanField(default=True, help_text='Allow users to share documents via email'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_backend',
            field=models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='Email backend (SMTP, Console, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_from_address',
            field=models.EmailField(blank=True, help_text="Default 'From' email address", max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_from_name',
            field=models.CharField(default='Doctype Engine', help_text="Default 'From' name", max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', help_text='SMTP server hostname', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTP password (stored encrypted)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='SMTP username/email address', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_port',
            field=models.IntegerField(default=587, help_text='SMTP server port', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_rate_limit',
            field=models.IntegerField(default=50, help_text='Maximum emails per user per hour', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL encryption (mutually exclusive with TLS)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS encryption'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_email',
            field=models.BooleanField(default=False, help_text='Enable email functionality'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_incoming_email',
            field=models.BooleanField(default=False, help_text='Enable incoming email processing'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='imap_host',
            field=models.CharField(blank=True, default='imap.gmail.com', help_text='IMAP server hostname', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='imap_password',
            field=models.CharField(blank=True, help_text='IMAP password (stored encrypted)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='imap_port',
            field=models.IntegerField(default=993, help_text='IMAP server port', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='imap_use_ssl',
            field=models.BooleanField(default=True, help_text='Use SSL for IMAP connection'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='imap_username',
            field=models.CharField(blank=True, help_text='IMAP username/email address', max_length=255),
        ),
    ]
