# Generated by Django 5.2.8 on 2026-06-03 14:47

import core.security_models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings_allow_document_sharing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allowed_attachment_extensions',
            field=models.JSONField(blank=True, default=core.security_models.default_attachment_extensions, help_text='List of allowed file extensions (without the dot), e.g. ["pdf", "png", "docx"]. Empty list allows any extension.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_attachment_size_mb',
            field=models.IntegerField(default=10, help_text='Maximum size (MB) for a single document attachment', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1024)]),
        ),
    ]
