# Generated by Django 5.2.9 on 2025-12-03 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(help_text='JSON schema definition with fields, permissions, hooks')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_submittable', models.BooleanField(default=False, help_text='Can documents be submitted/approved')),
                ('is_single', models.BooleanField(default=False, help_text='Single doctype (only one document)')),
                ('is_child', models.BooleanField(default=False, help_text='Child table doctype')),
                ('is_tree', models.BooleanField(default=False, help_text='Tree/hierarchical structure')),
                ('naming_rule', models.CharField(blank=True, help_text='e.g., {module}-{####}', max_length=255)),
                ('autoname', models.CharField(blank=True, choices=[('prompt', 'Prompt User'), ('autoincrement', 'Auto Increment'), ('field', 'Based on Field'), ('expression', 'Expression'), ('uuid', 'UUID')], default='autoincrement', max_length=50)),
                ('has_permissions', models.BooleanField(default=True)),
                ('track_changes', models.BooleanField(default=True, help_text='Version history')),
                ('track_views', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('title_field', models.CharField(blank=True, help_text='Field to use as document title', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_custom', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doctypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctypeHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_type', models.CharField(choices=[('before_insert', 'Before Insert'), ('after_insert', 'After Insert'), ('before_save', 'Before Save'), ('after_save', 'After Save'), ('before_submit', 'Before Submit'), ('after_submit', 'After Submit'), ('before_delete', 'Before Delete'), ('after_delete', 'After Delete'), ('on_change', 'On Field Change')], max_length=50)),
                ('action_type', models.CharField(choices=[('python', 'Python Code'), ('webhook', 'Webhook'), ('email', 'Send Email'), ('notification', 'System Notification')], max_length=50)),
                ('python_code', models.TextField(blank=True, help_text='Python code to execute')),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_headers', models.JSONField(blank=True, default=dict)),
                ('email_template', models.TextField(blank=True)),
                ('email_recipients', models.JSONField(blank=True, default=list)),
                ('condition', models.TextField(blank=True, help_text='When to trigger this hook')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='doctypes.doctype')),
            ],
            options={
                'ordering': ['doctype', 'hook_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Document data conforming to the doctype schema')),
                ('name', models.CharField(blank=True, db_index=True, help_text='Document identifier', max_length=255)),
                ('docstatus', models.IntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_group', models.BooleanField(default=False, help_text='Is this a group/folder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_documents', to=settings.AUTH_USER_MODEL)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='doctypes.doctype')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_documents', to=settings.AUTH_USER_MODEL)),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='doctypes.document')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Name of the link field in the source document', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_links', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(help_text='Document that contains the link field', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='doctypes.document')),
                ('target_document', models.ForeignKey(help_text='Document being linked to', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_links', to='doctypes.document')),
            ],
            options={
                'ordering': ['source_document', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLinkMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_links_out', to='doctypes.document')),
                ('target_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multi_links_in', to='doctypes.document')),
            ],
            options={
                'ordering': ['source_document', 'field_name', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('personal_message', models.TextField(blank=True)),
                ('share_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='doctypes.document')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('data_snapshot', models.JSONField(help_text='Complete data at this version')),
                ('changes', models.JSONField(help_text='What changed from previous version')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='doctypes.document')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=100)),
                ('color', models.CharField(default='#3498db', help_text='Hex color code', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('is_custom', models.BooleanField(default=True, help_text='Custom vs system module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_modules', to=settings.AUTH_USER_MODEL)),
                ('parent_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='doctypes.module')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='doctype',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctypes', to='doctypes.module'),
        ),
        migrations.CreateModel(
            name='NamingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=100)),
                ('current_value', models.IntegerField(default=0)),
                ('padding', models.IntegerField(default=4, help_text='Number of digits')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naming_series', to='doctypes.doctype')),
            ],
            options={
                'ordering': ['doctype', 'series_name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('report_type', models.CharField(choices=[('query', 'Query Builder'), ('sql', 'SQL Query'), ('python', 'Python Script')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('query', models.TextField(help_text='Query definition')),
                ('columns', models.JSONField(default=list, help_text='Column definitions')),
                ('filters', models.JSONField(default=list, help_text='Available filters')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, to='auth.group')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='doctypes.doctype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('workflow_data', models.JSONField(help_text='Workflow definition with states and transitions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='doctypes.doctype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('position_x', models.IntegerField(default=0, help_text='X position in visual designer')),
                ('position_y', models.IntegerField(default=0, help_text='Y position in visual designer')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='doctypes.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentWorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_changed_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state', to='doctypes.document')),
                ('state_changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctypes.workflow')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctypes.workflowstate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('condition', models.TextField(blank=True, help_text='Python expression for conditional transition')),
                ('require_comment', models.BooleanField(default=False)),
                ('actions', models.JSONField(default=list, help_text='Actions to execute on transition')),
                ('allowed_roles', models.ManyToManyField(blank=True, to='auth.group')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='doctypes.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='doctypes.workflowstate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='doctypes.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('fieldtype', models.CharField(max_length=50)),
                ('options', models.JSONField(default=dict, help_text='Field-specific options')),
                ('default_value', models.TextField(blank=True)),
                ('insert_after', models.CharField(blank=True, help_text='Field to insert after', max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_readonly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='doctypes.doctype')),
            ],
            options={
                'ordering': ['doctype', 'insert_after'],
                'unique_together': {('doctype', 'fieldname')},
            },
        ),
        migrations.CreateModel(
            name='DoctypePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_submit', models.BooleanField(default=False)),
                ('can_cancel', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_import', models.BooleanField(default=False)),
                ('permission_condition', models.TextField(blank=True, help_text='Python expression for conditional access')),
                ('apply_user_permissions', models.BooleanField(default=True)),
                ('read_only_fields', models.JSONField(blank=True, default=list)),
                ('hidden_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='doctypes.doctype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'ordering': ['doctype', 'role'],
                'unique_together': {('doctype', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doctype', '-created_at'], name='doctypes_do_doctype_0db8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlink',
            index=models.Index(fields=['source_document', 'field_name'], name='doctypes_do_source__ee8229_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlink',
            index=models.Index(fields=['target_document'], name='doctypes_do_target__beb62f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentlink',
            unique_together={('source_document', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='documentlinkmultiple',
            index=models.Index(fields=['source_document', 'field_name'], name='doctypes_do_source__d28030_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlinkmultiple',
            index=models.Index(fields=['target_document'], name='doctypes_do_target__a6f68a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['document', 'recipient_email'], name='doctypes_do_documen_d1bdde_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['shared_by', '-sent_at'], name='doctypes_do_shared__813384_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', '-version_number'], name='doctypes_do_documen_4d76da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['slug', 'is_active'], name='doctypes_mo_slug_b0d81f_idx'),
        ),
        migrations.AddIndex(
            model_name='doctype',
            index=models.Index(fields=['slug', 'status'], name='doctypes_do_slug_561df6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='namingseries',
            unique_together={('doctype', 'series_name')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowstate',
            unique_together={('workflow', 'name')},
        ),
        migrations.AddIndex(
            model_name='documentworkflowstate',
            index=models.Index(fields=['workflow', 'current_state'], name='doctypes_do_workflo_f050df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtransition',
            unique_together={('workflow', 'from_state', 'to_state')},
        ),
    ]
