# Generated by Django 5.2.9 on 2025-12-04 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctypes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('cleanup', 'Cleanup'), ('archive', 'Archive'), ('delete', 'Delete')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resource_type', models.CharField(max_length=50)),
                ('records_affected', models.IntegerField(default=0)),
                ('retention_policy', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Data Retention Log',
                'verbose_name_plural': 'Data Retention Logs',
                'db_table': 'data_retention_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rate Limit Log',
                'verbose_name_plural': 'Rate Limit Logs',
                'db_table': 'rate_limit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('auth_failed', 'Authentication Failed'), ('perm_denied', 'Permission Denied'), ('rate_limit', 'Rate Limit Exceeded'), ('suspicious', 'Suspicious Activity'), ('data_breach', 'Potential Data Breach'), ('integrity_fail', 'Data Integrity Check Failed'), ('csrf_fail', 'CSRF Validation Failed')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('resource', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('alerted', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'db_table': 'security_event',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VersionAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('list', 'List Versions'), ('view', 'View Version'), ('compare', 'Compare Versions'), ('restore', 'Restore Version'), ('download', 'Download Version')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('query_params', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Version Access Log',
                'verbose_name_plural': 'Version Access Logs',
                'db_table': 'version_access_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VersionIntegrityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField(db_index=True)),
                ('expected_hash', models.CharField(max_length=64)),
                ('actual_hash', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Version Integrity Log',
                'verbose_name_plural': 'Version Integrity Logs',
                'db_table': 'version_integrity_log',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddField(
            model_name='documentversion',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of data_snapshot', max_length=64),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='signature',
            field=models.TextField(blank=True, help_text='HMAC signature for tamper detection'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['data_hash'], name='doctypes_do_data_ha_a2aae0_idx'),
        ),
        migrations.AddField(
            model_name='dataretentionlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='versionaccesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='versionaccesslog',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='doctypes.documentversion'),
        ),
        migrations.AddField(
            model_name='versionintegritylog',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='versionintegritylog',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_checks', to='doctypes.documentversion'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['user', 'action', 'timestamp'], name='rate_limit__user_id_71ac14_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='security_ev_event_t_0b896c_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['severity', 'timestamp'], name='security_ev_severit_070cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['resolved', 'timestamp'], name='security_ev_resolve_368cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', 'timestamp'], name='security_ev_user_id_d0f1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='versionaccesslog',
            index=models.Index(fields=['user', 'timestamp'], name='version_acc_user_id_31e2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='versionaccesslog',
            index=models.Index(fields=['version', 'timestamp'], name='version_acc_version_26eb56_idx'),
        ),
        migrations.AddIndex(
            model_name='versionaccesslog',
            index=models.Index(fields=['action', 'timestamp'], name='version_acc_action_e6a55c_idx'),
        ),
        migrations.AddIndex(
            model_name='versionaccesslog',
            index=models.Index(fields=['success', 'timestamp'], name='version_acc_success_c62f36_idx'),
        ),
        migrations.AddIndex(
            model_name='versionaccesslog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='version_acc_ip_addr_eac46a_idx'),
        ),
        migrations.AddIndex(
            model_name='versionintegritylog',
            index=models.Index(fields=['version', 'checked_at'], name='version_int_version_2ba336_idx'),
        ),
        migrations.AddIndex(
            model_name='versionintegritylog',
            index=models.Index(fields=['passed', 'checked_at'], name='version_int_passed_3ec40d_idx'),
        ),
    ]
