# Generated by Django 5.2.8 on 2025-12-01 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doctypes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctype',
            name='autoname',
            field=models.CharField(blank=True, choices=[('prompt', 'Prompt User'), ('autoincrement', 'Auto Increment'), ('field', 'Based on Field'), ('expression', 'Expression'), ('uuid', 'UUID')], default='autoincrement', max_length=50),
        ),
        migrations.AddField(
            model_name='doctype',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='doctype',
            name='has_permissions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctype',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctype',
            name='is_child',
            field=models.BooleanField(default=False, help_text='Child table doctype'),
        ),
        migrations.AddField(
            model_name='doctype',
            name='is_custom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctype',
            name='is_single',
            field=models.BooleanField(default=False, help_text='Single doctype (only one document)'),
        ),
        migrations.AddField(
            model_name='doctype',
            name='is_submittable',
            field=models.BooleanField(default=False, help_text='Can documents be submitted/approved'),
        ),
        migrations.AddField(
            model_name='doctype',
            name='is_tree',
            field=models.BooleanField(default=False, help_text='Tree/hierarchical structure'),
        ),
        migrations.AddField(
            model_name='doctype',
            name='naming_rule',
            field=models.CharField(blank=True, help_text='e.g., {module}-{####}', max_length=255),
        ),
        migrations.AddField(
            model_name='doctype',
            name='title_field',
            field=models.CharField(blank=True, help_text='Field to use as document title', max_length=255),
        ),
        migrations.AddField(
            model_name='doctype',
            name='track_changes',
            field=models.BooleanField(default=True, help_text='Version history'),
        ),
        migrations.AddField(
            model_name='doctype',
            name='track_views',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='docstatus',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Cancelled')], default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Is this a group/folder'),
        ),
        migrations.AddField(
            model_name='document',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='Document identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='doctypes.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='schema',
            field=models.JSONField(help_text='JSON schema definition with fields, permissions, hooks'),
        ),
        migrations.CreateModel(
            name='DoctypeHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_type', models.CharField(choices=[('before_insert', 'Before Insert'), ('after_insert', 'After Insert'), ('before_save', 'Before Save'), ('after_save', 'After Save'), ('before_submit', 'Before Submit'), ('after_submit', 'After Submit'), ('before_delete', 'Before Delete'), ('after_delete', 'After Delete'), ('on_change', 'On Field Change')], max_length=50)),
                ('action_type', models.CharField(choices=[('python', 'Python Code'), ('webhook', 'Webhook'), ('email', 'Send Email'), ('notification', 'System Notification')], max_length=50)),
                ('python_code', models.TextField(blank=True, help_text='Python code to execute')),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_headers', models.JSONField(blank=True, default=dict)),
                ('email_template', models.TextField(blank=True)),
                ('email_recipients', models.JSONField(blank=True, default=list)),
                ('condition', models.TextField(blank=True, help_text='When to trigger this hook')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='doctypes.doctype')),
            ],
            options={
                'ordering': ['doctype', 'hook_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=100)),
                ('color', models.CharField(default='#3498db', help_text='Hex color code', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('is_custom', models.BooleanField(default=True, help_text='Custom vs system module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_modules', to=settings.AUTH_USER_MODEL)),
                ('parent_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='doctypes.module')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='doctype',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctypes', to='doctypes.module'),
        ),
        migrations.CreateModel(
            name='NamingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=100)),
                ('current_value', models.IntegerField(default=0)),
                ('padding', models.IntegerField(default=4, help_text='Number of digits')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naming_series', to='doctypes.doctype')),
            ],
            options={
                'ordering': ['doctype', 'series_name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('report_type', models.CharField(choices=[('query', 'Query Builder'), ('sql', 'SQL Query'), ('python', 'Python Script')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('query', models.TextField(help_text='Query definition')),
                ('columns', models.JSONField(default=list, help_text='Column definitions')),
                ('filters', models.JSONField(default=list, help_text='Available filters')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, to='auth.group')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='doctypes.doctype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('workflow_data', models.JSONField(help_text='Workflow definition with states and transitions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='doctypes.doctype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('position_x', models.IntegerField(default=0, help_text='X position in visual designer')),
                ('position_y', models.IntegerField(default=0, help_text='Y position in visual designer')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='doctypes.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentWorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_changed_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_state', to='doctypes.document')),
                ('state_changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctypes.workflow')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctypes.workflowstate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('condition', models.TextField(blank=True, help_text='Python expression for conditional transition')),
                ('require_comment', models.BooleanField(default=False)),
                ('actions', models.JSONField(default=list, help_text='Actions to execute on transition')),
                ('allowed_roles', models.ManyToManyField(blank=True, to='auth.group')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='doctypes.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='doctypes.workflowstate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='doctypes.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('fieldtype', models.CharField(max_length=50)),
                ('options', models.JSONField(default=dict, help_text='Field-specific options')),
                ('default_value', models.TextField(blank=True)),
                ('insert_after', models.CharField(blank=True, help_text='Field to insert after', max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_readonly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='doctypes.doctype')),
            ],
            options={
                'ordering': ['doctype', 'insert_after'],
                'unique_together': {('doctype', 'fieldname')},
            },
        ),
        migrations.CreateModel(
            name='DoctypePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_submit', models.BooleanField(default=False)),
                ('can_cancel', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_import', models.BooleanField(default=False)),
                ('permission_condition', models.TextField(blank=True, help_text='Python expression for conditional access')),
                ('apply_user_permissions', models.BooleanField(default=True)),
                ('read_only_fields', models.JSONField(blank=True, default=list)),
                ('hidden_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='doctypes.doctype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'ordering': ['doctype', 'role'],
                'unique_together': {('doctype', 'role')},
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('data_snapshot', models.JSONField(help_text='Complete data at this version')),
                ('changes', models.JSONField(help_text='What changed from previous version')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='doctypes.document')),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['document', '-version_number'], name='doctypes_do_documen_4d76da_idx')],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['slug', 'is_active'], name='doctypes_mo_slug_b0d81f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='namingseries',
            unique_together={('doctype', 'series_name')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowstate',
            unique_together={('workflow', 'name')},
        ),
        migrations.AddIndex(
            model_name='documentworkflowstate',
            index=models.Index(fields=['workflow', 'current_state'], name='doctypes_do_workflo_f050df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtransition',
            unique_together={('workflow', 'from_state', 'to_state')},
        ),
    ]
