# Generated by Django 5.2.8 on 2025-12-02 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctypes', '0003_documentshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Name of the link field in the source document', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_links', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(help_text='Document that contains the link field', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='doctypes.document')),
                ('target_document', models.ForeignKey(help_text='Document being linked to', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_links', to='doctypes.document')),
            ],
            options={
                'ordering': ['source_document', 'field_name'],
                'indexes': [models.Index(fields=['source_document', 'field_name'], name='doctypes_do_source__ee8229_idx'), models.Index(fields=['target_document'], name='doctypes_do_target__beb62f_idx')],
                'unique_together': {('source_document', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='DocumentLinkMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_links_out', to='doctypes.document')),
                ('target_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multi_links_in', to='doctypes.document')),
            ],
            options={
                'ordering': ['source_document', 'field_name', 'order'],
                'indexes': [models.Index(fields=['source_document', 'field_name'], name='doctypes_do_source__d28030_idx'), models.Index(fields=['target_document'], name='doctypes_do_target__a6f68a_idx')],
            },
        ),
    ]
