# Generated by Django 5.2.8 on 2026-02-15 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctypes', '0004_documentlink_documentlinkmultiple'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='doctypes.document')),
                ('from_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_from', to='doctypes.workflowstate')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_to', to='doctypes.workflowstate')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='doctypes.workflowtransition')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctypes.workflow')),
            ],
            options={
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['document', '-performed_at'], name='doctypes_wo_documen_e3ef2a_idx')],
            },
        ),
    ]
