# Generated by Django 5.2.8 on 2026-06-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctypes', '0006_documentattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('template', models.TextField(blank=True, help_text='HTML body, Django template syntax (e.g. {{ doc.name }}, {{ data.field }}). If blank, a generic field table is rendered.')),
                ('css', models.TextField(blank=True, help_text='Extra CSS for the printable page')),
                ('letterhead', models.TextField(blank=True, help_text='HTML shown at the top of every page')),
                ('header', models.TextField(blank=True, help_text='HTML shown above the body')),
                ('footer', models.TextField(blank=True, help_text='HTML shown below the body')),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter'), ('Legal', 'Legal')], default='A4', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Default format for this doctype')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_formats', to='doctypes.doctype')),
            ],
            options={
                'ordering': ['doctype', 'name'],
            },
        ),
    ]
